config/routes.rb
Rails.application.routes.draw do

  devise_for :users
   get "home/about"=>"homes#about", as:"about"
   root to:"homes#top"

  resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update]do
   resources :book_comments, only: [:create,:destroy]
    resource :favorite,only: [:create,:destroy]
  end
  resources :users, only: [:show, :edit, :index, :update]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
belongs_to :user
has_many :favorite, dependent: :destroy
has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

def favorite_by?(user)
  favorite.exists?(user_id: user.id)
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #フォローの関係(２行目は一覧画面で使う)自分がフォローする
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :follower

  #フォロワーの関係(２行目は一覧画面で使う)自分がフォローされる
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :follower, through: :follower_relationships, source: :follower
  # フォローしたときの処理
  def follow!(user)
    following_relationships.create!(following_id: user.id)
  end

  # フォローを外すときの処理
  def unfollow!(user)
    relation = following_relationships.find_by!(following_id: user.id)
    relation.destroy!
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
    #following_relationships.exists?(following_id: user.id)
  end

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end




  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
    end



end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.new(book_comment_params)
    book_comment.book_id = @book.id
    book_comment.save
    redirect_to book_path(@book)
  end

 def destroy
 BookComment.find(params[:id]).destroy
 redirect_to book_path(params[:book_id])
 end


  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :correct_user, only: [:edit, :update]
      before_action :authenticate_user!, except: [:top]

  def new
    @book = Book.new
  end

  def show
   @books = Book.all
   @book_new = Book.new
   @book= Book.find(params[:id])
   @user = @book.user
   @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book),  notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end


  def edit
    @book = Book.find(params[:id])
  end


 def update
   @book = Book.find(params[:id])
    if @book.update(book_params)
   redirect_to book_path(@book), notice: "You have updated book successfully."
   else
    render :edit
   end
 end


def destroy
  @book = Book.find(params[:id])
  @book.destroy
  redirect_to books_path
end


  private
  def book_params
      params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
     favorites = current_user.favorites.new(book_id: @book.id)
     favorites.save
     redirect_to book_path(@book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorites = current_user.favorites.find_by(book_id: @book.id)
    favorites.destroy
    redirect_to book_path(@book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
   before_action :authenticate_user!
  # フォローするとき
  def create
    user = User.find(params[:user_id])
    current_user.follow!(user)
	redirect_to request.referer
  end

  # フォロー外すとき
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow!(user)
    redirect_to request.referer
  end

  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
	@users = user.followings
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
	@users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:top]
  before_action :correct_user, only: [:edit, :update]

  def index
    @user = current_user
    p @users = User.all
    @books = @user.books
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to  user_path(@user.id), notice: "You have updated user successfully."
  else
    render :edit
  end
end

private

def user_params
 params.require(:user).permit(:introduction, :name, :profile_image, :title, :body)
end

 def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user)) unless @user == current_user
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/test.html.erb
<h1>test1</h1>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Editing Book</h2>
    <%= form_with model:@book, url: book_path do |f| %>
      <div class="form-group">
        <%= f.label :Title %>
        <%= f.text_field :title, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :Opinion %>
        <%= f.text_area :body, class: "form-control introduction" %>
      </div>

      <div class="form-group">
            <%= f.submit 'Update Book', class:"btn btn-secondary" %>

          </div>
    <% end %>

    <%= link_to "Show",book_path(@book.id) %>|
    <%= link_to "Back",books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
          <%= image_tag @user.get_profile_image(100,100) %>
          <table class="table">
             <tbody>
               <tr>
                  <th>name</th>
                  <th><%= @user.name %></th>
                  </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= @user.introduction %></th>
                </tr>
              </tbody>
            </table>
      <div class="row">
         <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog edit-user_52324"></i>
         <% end %>
      </div>
        <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
               <div class="form-group">
                     <label for="book_title">Title</label>
                     <%= f.text_field :title, class:"form-control book_title" %>
                </div>
                <div class="form-group">
                     <label for="form_opinion">Opinion</label>
                      <%= f.text_area :body, class:"form-control  book_body" %>
                </div>
                <div class="form-group">
                      <%= f.submit 'Create Book', class:"btn btn-success" %>
                </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
              <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
              </tr>
        </thead>

 <!--ここにブック投稿一覧がくる-->
         <tbody>
           <% @books.each do |book| %>
              <tr>
                <td>
                   <div class="row">
                       <%= link_to user_path(book.user.id) do %>
                          <%= image_tag @user.get_profile_image(50,50) %>
                       <% end %>
                   </div>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
              </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
         <%= image_tag @user.get_profile_image(100,100) %>
          <table class="table">
             <tbody>
               <tr>
                  <th>name</th>
                  <th><%=@user.name %></th>
                  </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= @user.introduction %></th>
                </tr>
              </tbody>
            </table>

    <div class="row">
         <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog edit-user_52324"></i>
         <% end %>
      </div>

        <h2 class="mt-3">New book</h2>
      <%= form_with model: @book_new do |f| %>
         <div class="form-group">
           <label for="book_title">Title</label>
           <%= f.text_field :title, class:"form-control book_title" %>
          </div>
          <div class="form-group">

           <label for="form_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control  book_body" %>
          </div>


          <div class="form-group">
            <%= f.submit "Create Book", class:"btn btn-success" %>
          </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table ">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do  %>
            <%= image_tag @user.get_profile_image(100,100) %><br>
             <%= @user.name %>
            </td>

            <% end %>
            <td><%= link_to @book.title,  book_path(@book) %></td>
            <td><%= @book.body %></td>

           <td>

            <% if @book.favorite_by?(current_user) %>
              <p>
                <%= link_to book_favorite_path(@book), method: :delete do %>
                  ♥<%= @book.favorite.count %> いいね
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorite_path(@book), method: :post do %>
                  ♡<%= @book.favorite.count %> いいね
                <% end %>
              </p>
            <% end %>

          </td>

            <% if @user.id == current_user.id %>
             <td>
                <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-group-sm btn-success" %>
             </td>
             <td>
                <%= link_to "Destroy", book_path(@book.id) , method: :delete, class:"btn btn-danger btn-group-sm"  %>
             </td>
             <% end %>
          </tr>
        </tbody>
        </table>

        <div>
          <p>コメント件数：<%= @book.book_comments.count %></p>
          <% @book.book_comments.each do |book_comment| %>
            <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
            <%= book_comment.user.name %>
            <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
              <% if book_comment.user == current_user %>
                <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
              <% end %>
          <% end %>
        </div>

        <div>
          <%= form_with model: [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>
        </div>


     </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in",new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up",new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: 'navbar-brand' do %>
            Bookers
          <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>

              <li>
                <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li>

                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i>Users
                <% end %>
              </li>

              <li>
                <%= link_to books_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i>Log out
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
     </nav>
  </header>



<p id="notice"><%= notice %></p>

    <%= yield %>



     <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>




  </body>
</html>

app/views/relationships/_follow_list.html.erb
<% if users.exists? %>
  <% users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<h1>Relationships#followers</h1>
<p>Find me in app/views/relationships/followers.html.erb</p>

app/views/relationships/followings.html.erb
<h1>Relationships#followings</h1>
<p>Find me in app/views/relationships/followings.html.erb</p>

app/views/users/edit.html.erb
<!--4⃣バリデーション機能実装-->
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user do |f| %>
      <div class="form-group">
        <%= f.label :Name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <!--クリックするとエラー-->
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
            <%= f.submit 'Update User', class:"btn btn-secondary" %>

          </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
         <%= image_tag @user.get_profile_image(100,100) %>
            <table class="table">
               <tbody>
                 <tr>
                 <th>name</th>
                 <th><%= @user.name %></th>
                 </tr>
                 <tr>
                 <th>introduction</th>
                 <th><%=@user.introduction %></th>
                 </tr>
              </tbody>
          </table>

<!--ユーザー編集ページ-->
    <div class="row">
         <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog edit-user_52324"></i>
         <% end %>
      </div>

<!--ブック投稿ページ-->
        <h2 class="mt-3">New book</h2>
          <%= form_with model: @book do |f| %>
            <div class="form-group">
            <label for="book_title">Title</label>
                 <%= f.text_field :title, class:"form-control book_title" %>
            </div>
            <div class="form-group">
                <label for="form_opinion">Opinion</label>
                <%= f.text_area :body, class:"form-control  book_body" %>
            </div>

            <div class="form-group">
              <%= f.submit 'Create Book', class:"btn btn-success" %>
            </div>

          <%end %>
    </div>

        <!--ブック投稿一覧-->

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
                <thead>
                  <tr>
                     <th>image</th>
                     <th>name</th>
                     <th></th>
                     <th colspan="3"></th>
                  </tr>
                </thead>

                 <tbody>
               <% @users.each do |user| %>
                    <tr>
                       <td>
                       <%= image_tag user.get_profile_image(100,100) %>
                       </td>
                       <td><%= user.name %></td>
                       <td><%= link_to "Show", user_path(user) %></td>
                   </tr>
                <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
       <h2>User info</h2>
       <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
         <tbody>
           <tr>
              <th>name</th>
              <th><%= @user.name %></th>
              </tr>
            <tr>
              <th>introduction</th>
              <th><%=@user.introduction %></th>
            </tr>
          </tbody>
        </table>

        <% if @user == current_user %>
          <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        <%else %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
          <% end %>
        <% end %>




        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, url: books_path do |f| %>
         <div class="form-group">
           <label for="book_title">Title</label>
           <%= f.text_field :title, class:"form-control book_title" %>
          </div>
          <div class="form-group">

           <label for="form_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control  book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
        <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

 <!--ここにブック投稿一覧がくる-->
         <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(@user)  do%>
                   <%= image_tag @user.get_profile_image(100,100) %>
                   <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>

              </tr>
            <% end %>
         </tbody>
      </table>
    </div>
  </div>
</div>